name: Action test on MacOS

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  macos-min:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos-max:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          source_branch: "main"
          destination_branch: "test-macos-max"
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: "An automated PR"
          pr_reviewer: "GuillaumeFalourd"
          pr_assignee: "GuillaumeFalourd"
          pr_label: "test"
          pr_milestone: "Milestone 1"
          pr_draft: true
          pr_allow_empty: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
