name: Action test
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./
        name: test-min
        if: failure() || success()
      - uses: ./
        name: test-title-only
        if: failure() || success()
        with:
          pr_title: "Pulling ${{ github.ref_name }} into main"
      - uses: ./
        name: test-body-only
        if: failure() || success()
        with:
          pr_body: "Pulling ${{ github.ref_name }} into main"
      - uses: ./
        name: test-max
        if: failure() || success()
        with:
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: "An automated PR"
          pr_reviewer: "GuillaumeFalourd"
          pr_assignee: "GuillaumeFalourd"
          pr_label: "test"
          pr_milestone: "Milestone 1"
          pr_draft: true
          pr_allow_empty: true
