name: Action test on Ubuntu

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ubuntu-min:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo -e "Output of pr job is:\n${{ tojson(steps.pr.outputs) }}"

  ubuntu-max:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: pr
        with:
          pr_title: "Pulling ${{ github.ref_name }} into main"
          pr_body: "An automated PR"
          pr_reviewer: "GuillaumeFalourd"
          pr_assignee: "GuillaumeFalourd"
          pr_label: "test"
          pr_milestone: "Milestone 1"
          pr_draft: true
          pr_allow_empty: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo -e "Output of pr job is:\n${{ tojson(steps.pr.outputs) }}"
