name: Action test on Windows

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  windows-min:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-max:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./
        with:
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: "An automated PR"
          pr_reviewer: "GuillaumeFalourd"
          pr_assignee: "GuillaumeFalourd"
          pr_label: "test"
          pr_milestone: "Milestone 1"
          pr_draft: true
          pr_allow_empty: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
